export const projectsList = [
  {
    id: 1,
    type: "app",
    videoName: "mainpage.mov",
    projectName: "Test Board 1",
    mainInfo: "test info test info test info",
    text: "What is Trello? Trello is the visual tool that empowers your team to manage any type of project, workflow, or task tracking. Add files, checklists, or even automation: Customize it all for how your team works best. Just sign up, create a board, and you’re off!",
    tools: ["React", "TypeScript", "StyledComponents"],
    website: "https://trello.com/",
    github: "https://github.com/dariacz12",
    images: [
      { name: "avatarDCz.jpg", caption: "Class management" },
      { name: "avatarDCz.jpg", caption: " Daria" },
      { name: "computer.png", caption: "Class management" },
      { name: "avatarDCz.jpg", caption: " Daria" },
    ],
  },
  {
    id: 2,
    type: "webpage",
    videoName: "mainpage.mov",
    projectName: "Test Board 2",
    mainInfo: "test info test info test info",
    text: "What is Trello? Trello is the visual tool that empowers your team to manage any type of project, workflow, or task tracking. Add files, checklists, or even automation: Customize it all for how your team works best. Just sign up, create a board, and you’re off!",
    tools: ["React", "TypeScript", "StyledComponents"],
    website: "https://trello.com/",
    github: "https://github.com/dariacz12",
    images: [
      { name: "computer.png", caption: "Class management" },
      { name: "avatarDCz.jpg", caption: " Daria" },
    ],
  },
  {
    id: 3,
    type: "webpage",
    videoName: "mainpage.mov",
    projectName: "Test Board 3",
    mainInfo: "test info test info test info",
    text: "What is Trello? Trello is the visual tool that empowers your team to manage any type of project, workflow, or task tracking. Add files, checklists, or even automation: Customize it all for how your team works best. Just sign up, create a board, and you’re off!",
    tools: ["React", "TypeScript", "StyledComponents"],
    website: "https://trello.com/",
    github: "https://github.com/dariacz12",
    images: [
      { name: "computer.png", caption: "Class management" },
      { name: "avatarDCz.jpg", caption: " Daria" },
    ],
  },
  {
    id: 4,
    type: "webpage",
    videoName: "mainpage.mov",
    projectName: "Test Board 4",
    mainInfo: "test info test info test info",
    text: "What is Trello? Trello is the visual tool that empowers your team to manage any type of project, workflow, or task tracking. Add files, checklists, or even automation: Customize it all for how your team works best. Just sign up, create a board, and you’re off!",
    tools: ["React", "TypeScript", "StyledComponents"],
    website: "https://trello.com/",
    github: "https://github.com/dariacz12",
    images: [
      { name: "computer.png", caption: "Class management" },
      { name: "avatarDCz.jpg", caption: " Daria" },
    ],
  },
];
