export const projectsList = [
  {
    id: 1,
    type: "app",
    videoName: require(`../public/video/theswiplovideo.mov`),
    projectName: "Swiplo",
    mainInfo: "Sign up for classes with the Swiplo mobile app",
    text: "The e-pass for customers using the package with the mobile application allows you to easily and quickly reflect the entrance by scanning the QR code by the reception employee. No more paper passes or magnetic cards that fill up your wallet! Push notifications allow you to quickly and cost-free communicate with clients of selected classes or with all students of the school. You can check who is using the application in the system. Everything that matters most is in your phone: push notifications, enrollment for classes, salary calculation, ONLINE payments, subscription form, SMS gate",
    tools: [
      "React Native",
      "TypeScript",
      " JavaScript",
      "NativeBase",
      "React Query",
      "React Hook Form",
      "Expo",
    ],
    website: "https://apps.apple.com/pl/app/swiplo/id1571483642",
    github: "",
    images: [
      { name: "phototskser1.png", caption: "Class management" },
      { name: "phototskser2.png", caption: " Daria" },
      { name: "phototskser3.png", caption: "Class management" },
      { name: "phototskser4.png", caption: " Daria" },
    ],
  },
  {
    id: 2,
    type: "webpage",
    videoName: require(`../public/video/thetaskservideo.mov`),
    projectName: "Taskser",
    mainInfo: "The visual tool that empowers to manage any type of project",
    text: "What is Taskser? In Taskser you can create boards, where you are able to add as many lists with diffrent tasks as you like. Whatever the project or process, boards keep tasks organized and work moving forward. Cards represent tasks and can hold all the information you need to get the job done. As you make progress, move cards across lists to show their status. At a glance, you can see everything from 'things to do' to 'aww yeah I did it!'- the diffrent stages of a task. Start as simple as To DO, Doing, or Done - or build a workflow custom fit your needs. Tasker offers adding files, checklists, covers, and many other actions with tasks. Just sign up, create a board, and you’re off! Simple, flexible, and powerful. All it takes are boards, lists, and cards to get a clear view of what needs to get done.",
    tools: [
      "React",
      "TypeScript",
      "React Query",
      "React Router Dom",
      "React Hook Form",
      "Chakra UI",
      "StyledComponents",
    ],
    website: "",
    github: "https://github.com/dariacz12/canban-app",
    images: [
      { name: "phototskser1.png", caption: "Login page" },
      { name: "phototskser2.png", caption: " Adding checklist to the task" },
      {
        name: "phototskser3.png",
        caption: "Main page with list of boards and 'Create New Board' Button",
      },
      { name: "phototskser4.png", caption: " Settings page" },
    ],
  },
  {
    id: 3,
    type: "webpage",
    videoName: require(`../public/video/thetaskservideo.mov`),
    projectName: "Test Board 3",
    mainInfo: "test info test info test info",
    text: "What is Trello? Trello is the visual tool that empowers your team to manage any type of project, workflow, or task tracking. Add files, checklists, or even automation: Customize it all for how your team works best. Just sign up, create a board, and you’re off!",
    tools: ["React", "TypeScript", "StyledComponents"],
    website: "https://trello.com/",
    github: "https://github.com/dariacz12",
    images: [
      { name: "computer.png", caption: "Class management" },
      { name: "avatarDCz.jpg", caption: " Daria" },
    ],
  },
  {
    id: 4,
    type: "webpage",
    videoName: require(`../public/video/thetaskservideo.mov`),
    projectName: "Test Board 4",
    mainInfo: "test info test info test info",
    text: "What is Trello? Trello is the visual tool that empowers your team to manage any type of project, workflow, or task tracking. Add files, checklists, or even automation: Customize it all for how your team works best. Just sign up, create a board, and you’re off!",
    tools: ["React", "TypeScript", "StyledComponents"],
    website: "https://trello.com/",
    github: "https://github.com/dariacz12",
    images: [
      { name: "computer.png", caption: "Class management" },
      { name: "avatarDCz.jpg", caption: " Daria" },
    ],
  },
];
