export const projectsList = [
  {
    id: 1,
    type: "app",
    videoName: `../video/theswiplovideo.mov`,
    projectName: "Swiplo",
    mainInfo: "Sign up for classes with the Swiplo mobile app",
    text: "The e-pass for customers using the package with the mobile application allows you to easily and quickly reflect the entrance by scanning the QR code by the reception employee. No more paper passes or magnetic cards that fill up your wallet! Push notifications allow you to quickly and cost-free communicate with clients of selected classes or with all students of the school. You can check who is using the application in the system. Everything that matters most is in your phone: push notifications, enrollment for classes, salary calculation, ONLINE payments, subscription form, SMS gate",
    tools: [
      "React Native",
      "TypeScript",
      "JavaScript",
      "NativeBase",
      "React Query",
      "React Hook Form",
      "Expo",
    ],
    website: "https://apps.apple.com/pl/app/swiplo/id1571483642",
    github: "",
    images: [
      { name: "swiplo-kalendarz-app.png", caption: "Calendar" },
      { name: "swiplo-zajecia-app.png", caption: " Classes" },
      { name: "swiplo-aktywne-karnety-app.png", caption: "Active passes" },
      { name: "swiplo-aktualnosci-aplikacja.png", caption: "Application news" },
    ],
  },
  {
    id: 2,
    type: "app",
    videoName: `../video/e2etestregistration.mov`,
    projectName: "App Programming Cards' Hub",
    mainInfo:
      "Learn programming languages through quizzes and flashcard-based learning.",
    text: "The Programming Cards' Hub App is a mobile application that helps users learn programming languages and prepare for technical interviews in an engaging and practical way. Forget memorizing answers — our interactive flashcards and quizzes are designed to help you truly understand each concept, so you can shine in interviews with real comprehension, not just definitions. The app lets you start learning for free through quiz-based exercises, and you can unlock full flashcard access by purchasing a physical product via our external store. Everything that matters for your learning journey is in one place: Quizzes and interactive exercises, Flashcards with practical knowledge, Interview preparation tools, Progress tracking and smart review system. Learn anywhere, anytime — and get ready to master programming with confidence.",
    tools: [
      "React Native",
      "TypeScript",
      "Expo",
      "React Query",
      "React Hook Form",
      "Strapi",
      "JavaScript",
    ],
    website: "",
    github: "https://github.com/dariacz12/app_programming_cards_hub",
    images: [
      { name: `../video/flipcardandquize.mov`, caption: "Flipcard and Quiz" },
      { name: `../video/cardblocked.mov`, caption: " Cards and Account" },
    ],
  },
  {
    id: 3,
    type: "webpage",
    videoName: `../video/programming_cars_hub_video.mov`,
    projectName: "Programming Cards' Hub",
    mainInfo:
      "Programming flashcards that will help you prepare for a job interview",
    text: "Flashcards with JavaScript for the price of an hour of work for a senior! Expand your knowledge based on the most frequently asked recruitment questions. Technical interviews will no longer be a problem!",
    tools: ["Wordpress", "Woocommerce", "Elementor Pro"],
    website: "https://fiszki-z-programowania.pl/",
    github: "",
    images: [
      { name: "programming_cars_hub1.png", caption: "Main page" },
      {
        name: "programming_cars_hub2.png",
        caption: "Product benefits with 3D box illustration that can be moved",
      },
      {
        name: "programming_cars_hub3.png",
        caption: "Presentation of the components of the flashcard",
      },
      { name: "programming_cars_hub4.png", caption: "Product shop" },
    ],
  },
  {
    id: 4,
    type: "webpage",
    videoName: `../video/thetaskservideo.mov`,
    projectName: "Taskser",
    mainInfo: "The visual tool that empowers to manage any type of project",
    text: "What is Taskser? In Taskser you can create boards, where you are able to add as many lists with diffrent tasks as you like. Whatever the project or process, boards keep tasks organized and work moving forward. Cards represent tasks and can hold all the information you need to get the job done. As you make progress, move cards across lists to show their status. At a glance, you can see everything from 'things to do' to 'aww yeah I did it!'- the diffrent stages of a task. Start as simple as To DO, Doing, or Done - or build a workflow custom fit your needs. Tasker offers adding files, checklists, covers, and many other actions with tasks. Just sign up, create a board, and you’re off! Simple, flexible, and powerful. All it takes are boards, lists, and cards to get a clear view of what needs to get done.",
    tools: [
      "React",
      "TypeScript",
      "React Query",
      "React Router Dom",
      "React Hook Form",
      "Chakra UI",
      "StyledComponents",
      "Strapi",
    ],
    website: "http://taskser.dariaczupreta.pl/",
    github: "https://github.com/dariacz12/canban-app",
    images: [
      { name: "phototskser1.png", caption: "Login page" },
      { name: "phototskser2.png", caption: " Adding checklist to the task" },
      {
        name: "phototskser3.png",
        caption: "Main page with list of boards and 'Create New Board' Button",
      },
      { name: "phototskser4.png", caption: " Settings page" },
    ],
  },
  //
  {
    id: 5,
    type: "webpage",
    videoName: `../video/handmade.mov`,
    projectName: "Irena's Handmade",
    mainInfo:
      "Explore the unique world of fairy tale with Irena's handmade products",
    text: "Welcome to Irena's Handmade, a haven for those who appreciate the beauty and uniqueness of handmade creations. Our business card webpage opens the door to a world where creativity knows no bounds, and each item is a testament to the passion and dedication of our skilled artisan, Irena. Our business card webpage is a portal to a world where tradition meets innovation, where ancient crafting techniques are given a contemporary twist, and where each product resonates with the heart and soul of its creator.",
    tools: ["React", "TypeScript", "StyledComponents", "FireBase"],
    website: "http://irenashandmade.dariaczupreta.pl/",
    github: "https://github.com/dariacz12/handmade-toys-shop",
    images: [
      { name: "handmade1.png", caption: "Product sub-page" },
      { name: "handmade2.png", caption: "Home page slider" },
      { name: "handmade3.png", caption: "List of the most purchased products" },
      { name: "handmade4.png", caption: "Product categories" },
    ],
  },
];
